repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
    # - id: terraform_checkov
    # - id: terraform_providers_lock
    # - id: terraform_tfsec
    # - id: terrascan
    # - id: tfupdate
    #   args:
    #   - --args=--version 1.2.7
    # - id: infracost_breakdown
    #   args:
    #     - --args=--path=.
    #   verbose: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-added-large-files
    - id: detect-private-key
