name: 'Deploy Connectivity Hub'

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - /modules/stack/hub
    - /modules/stack/bastion
    - /.github/workflows
  pull_request:
    branches:
    - main

jobs:
  invoke_nprd_hub_deploy:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: nprd
      tenant: db
      stack: hub
      key: hub_landing_zone
    secrets:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  invoke_nprd_hub_bastion_host_deploy:
    uses: ./.github/workflows/reusable.yml
    needs: invoke_nprd_hub_deploy
    with:
      environment: nprd
      tenant: db
      stack: bastion
      key: hub_bastion
    secrets:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  invoke_sim_hub_deploy:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: sim
      tenant: db
      stack: hub
      key: hub_landing_zone
    secrets:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  invoke_sim_hub_bastion_host_deploy:
    uses: ./.github/workflows/reusable.yml
    needs: invoke_sim_hub_deploy
    with:
      environment: sim
      tenant: db
      stack: bastion
      key: hub_bastion
    secrets:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}