name: 'Terraform Plan/Apply'

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  # call-workflow-1-in-local-repo:
    # uses: octo-org/this-repo/.github/workflows/workflow-1.yml@172239021f7ba04fe7327647b213799853a9eb89
  deploy_hub:
    uses: ./.github/workflows/reusable.yml
    # with:
      # command: echo "hi!"
  # call-workflow-in-another-repo:
    # uses: octo-org/another-repo/.github/workflows/workflow.yml@v1