name: "Deploy Connectivity Hub"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/stack/hub/**"
      - "modules/stack/bastion/**"
      - ".github/workflows/**"
      - "!.github/workflows/destroy_connectivity_hub.yml"
      - "!.github/workflows/terraform_plan_destroy.yml"
  pull_request:
    branches:
      - main
    paths:
      - "modules/stack/hub/**"
      - "modules/stack/bastion/**"
      - ".github/workflows/**"
      - "!.github/workflows/destroy_connectivity_hub.yml"
      - "!.github/workflows/terraform_plan_destroy.yml"

jobs:
  invoke_hub_deploy:
    strategy:
      fail-fast: false
      matrix:
        environment: [nprd, sim]
    name: ${{ matrix.environment }} Network and Firewall
    uses: ./.github/workflows/terraform_plan_apply.yml
    with:
      environment: ${{ matrix.environment }}
      tenant: db
      stack: hub
      key: hub_landing_zone
    secrets:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}

  invoke_hub_bastion_host_deploy:
    strategy:
      fail-fast: false
      matrix:
        environment: [nprd, sim]
    name: ${{ matrix.environment }} Bastion Host
    uses: ./.github/workflows/terraform_plan_apply.yml
    needs: invoke_hub_deploy
    with:
      environment: ${{ matrix.environment }}
      tenant: db
      stack: bastion
      key: hub_bastion
    secrets:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}

  invoke_hub_azuremonitor_deploy:
    strategy:
      fail-fast: false
      matrix:
        environment: [nprd, sim]
    name: ${{ matrix.environment }} Azure Monitor
    uses: ./.github/workflows/terraform_plan_apply.yml
    with:
      environment: ${{ matrix.environment }}
      tenant: db
      stack: azuremonitor
      key: hub_azure_monitor
    secrets:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
