name: Reusable workflow example

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - run: ${{ inputs.config-path }}
